confluence:
  image: cptactionhank/atlassian-confluence:latest
 # restart: always
  cpu_shares: 100
  mem_limit: 1GB 
  ports:
    - "80:8090"
  links:
    - postgres

postgres:
  image: postgres
  cpu_shares: 100
  mem_limit: 512MB
  ports:
    - "5432:5432"
  volumes:
    - ./scripts:/docker-entrypoint-initdb.d/
